# Generated by Django 5.2.13 on 2026-04-15 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='message',
        ),
        migrations.AddField(
            model_name='contact',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='contact_attachments/'),
        ),
        migrations.AddField(
            model_name='contact',
            name='category',
            field=models.IntegerField(blank=True, choices=[(1, 'Digital Foundations'), (2, 'Perception & Interaction'), (3, 'Growth Mechanics')], null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='country_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='sub_options',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
