# Generated by Django 5.2.13 on 2026-04-15 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_remove_contact_message_contact_attachment_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'ordering': ['-created_at'], 'verbose_name': 'Contact Submission', 'verbose_name_plural': 'Contact Submissions'},
        ),
        migrations.AddField(
            model_name='contact',
            name='message',
            field=models.TextField(blank=True, help_text='Optional message from the client.', null=True),
        ),
    ]
